//! Compiles proto/pulse/v1/*.proto into Rust at build time.
//!
//! Go bindings use `buf generate`. Rust bindings are generated by tonic-build
//! during compilation and are not committed.

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Vendored protoc so contributors don't need a system protobuf install.
    std::env::set_var("PROTOC", protoc_bin_vendored::protoc_bin_path()?);

    tonic_prost_build::configure()
        .compile_protos(&["../proto/pulse/v1/telemetry.proto"], &["../proto"])?;

    println!("cargo:rerun-if-changed=../proto");
    Ok(())
}
